<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class CreateOrderRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'userName'=>['required','string','max:100'],
            'phone_number'=>['required','numeric','max_digits:14'],
            'orderName'=>['required','string','max:100'],
            'orderDescription'=>['required','string','max:255'],
            'fromAddress'=>['required','string','max:255'],
            'toAddress'=>['required','string','max:255'],
            'price'=>['required','numeric','max:1000','min:10'],
            'date'=>['required','date','after:yesterday'],
            'time'=>['required','date_format:H:i'],
            'notes'=>['nullable','max:1000'],
        ];
    }

    function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
